# Generated by Django 5.0.3 on 2024-03-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTrade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='reviews',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(max_length=255),
        ),
    ]
