# Generated by Django 5.0.3 on 2024-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTrade', '0002_rename_content_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(),
        ),
    ]
