# Generated by Django 5.0.3 on 2024-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTrade', '0003_alter_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
