# Generated by Django 5.0.3 on 2024-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTrade', '0004_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
